---
version: "3.3"

services:
  code-server:
    image: ghokun/code-cv
    container_name: code-cv
    depends_on:
      - novnc
    environment:
      - DISPLAY=novnc:0.0
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password
      - SUDO_PASSWORD=password
    volumes:
      - ~/code-cv-config:/config
    networks:
      - x11
    ports:
      - 443:8443
    restart: unless-stopped

  novnc:
    container_name: novnc
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=800
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: unless-stopped

  rstudio:
    container_name: rstudio
    image: rocker/rstudio
    environment:
      - PASSWORD=yourpasswordhere
    networks:
      - x11
    ports:
      - 8787:8787
    volumes:
      - "$source_code_path:/home/rstudio"
    restart: unless-stopped

networks:
  x11:
