---
version: "3.3"

services:
  code-server:
    image: ghcr.io/ghokun/code-cv
    container_name: code-cv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password
      - SUDO_PASSWORD=password
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=800
    volumes:
      - $PROJECTS_PATH:/projects
    ports:
      - 443:8443
      - 8080:8080
    restart: unless-stopped
